### PR TITLE
Improve type checking on let statements

### PR DESCRIPTION
**Pull request by powerboat9**
Signed-off-by: Owen Avery <powerboat9.gamer@gmail.com>

---

Improves the typechecking of patterns in let statements.

### CODE REVIEW

**Review by philberty — APPROVED** [review]
Nice thanks for extracting this out on its own

**Comment by philberty** [comment]
Note before we can merge this you need to update opening PR comment here on github. Otherwise the bors merge commit will contain:

```
GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
Read contributing guidlines
make check-rust passes locally
Run clang-format
Added any relevant test cases to gcc/testsuite/rust/
```

I also think you could reword your commit message to be something like:


```
Reuse TypeCheckPattern on LetStmt's

Update Rust type-checking to reuse TypeCheckPattern on HIR::LetStmts.
This will unify the paths and improve error handling.
```

**Comment by powerboat9** [comment]
Ok, I rephrased both.

**Pull request merged**
