### PR TITLE
ci: Require commits check to pass for bors to merge and fix CI names

### LINKED ISSUE #1790: Add commits check to bors' list?
I think this should probably be done, but would hinder development when some PRs not needing Changelogs or having external commits (like GCC merges) have offending commits

### PR DESCRIPTION
**Pull request by CohenArthur**
ChangeLog:

	* .github/bors.toml: Add commit checkers.
	* .github/workflows/commit-format.yml: Rename commit checker jobs.

Fixes #1790

### CODE REVIEW

**Review by philberty — APPROVED** [review]
LGTM

**Comment by CohenArthur** [comment]
Hmph. Not sure why this isn't working. `bors` is maybe not happy about the fact that we're changing its configuration list like this? I'll rebase this PR manually.

**Pull request merged**
