### PR TITLE
[CL] first-half-update Changelogs for 24e9bd93f7..b3fcf322af96b766fed010256ea4302fa4168f7c

### PR DESCRIPTION
**Pull request by dkm**
https://github.com/Rust-GCC/gccrs/compare/82b64a2845707f2...b3fcf322af96b766fed010256ea4302fa4168f7c

So basically 6 commits from https://github.com/Rust-GCC/gccrs/tree/first-half-update, right after the ones in https://github.com/Rust-GCC/gccrs/pull/1757:

24e9bd93f7dcb96b31baace55a67cd905bc49998
777944e49c6ee90d63d479caa37204eee13d8160
6505e5a10d7ea3bd4f63ae33033f98a73191e2bb
d11e801180ac5ea48ec7e5b0e4581a2b5ebdb289
885fbd93f7a8a3f2b22c2c37c2cbcbb82da225b8
b3fcf322af96b766fed010256ea4302fa4168f7c

### CODE REVIEW

**Comment by dkm** [comment]
(messed up branch name, but won't rename it as this would close the PR. Should have been `dkm/gcc-patch-dev/24e9bd93f7-to-6505e5a10d7e`)

**Comment by dkm** [comment]
Will fix the error later tonight.

**Comment by dkm** [comment]
Failures caused by (I hope) missing pending commits in gcc-patch-dev branch....

**Comment by CohenArthur** [comment]
Closing in favor of #1841

**Pull request closed without merging**
