### PR TITLE
Lower ```if let```

### PR DESCRIPTION
**Pull request by powerboat9**
Depends on #2001 and #2002

### CODE REVIEW

**Comment by CohenArthur** [comment]
@powerboat9 I've converted your PR to a draft, feel free to convert it back for reviewing :)

**Comment by powerboat9** [comment]
Since its prerequisites have been merged and I've rebased, this should be ready now

**Review by philberty — APPROVED** [review]
LGTM does this still merge with your ExprStmt changes to the HIR?

**Comment by powerboat9** [comment]
It is rebased on the current master branch, so yes

**Review by CohenArthur — APPROVED** [review]

**Pull request merged**
