### PR TITLE
This adds supports for tuples

### PR DESCRIPTION
**Pull request by philberty**
More testing is required but this adds tuples apart from TupleStructs
which are parsed as CallExpr. This will be the primitives required to
finish that work.

Addresses #78

### CODE REVIEW

**Comment by philberty** [comment]
```
void main ()
{
  struct (i32,bool) a;
  struct (i32,f32) b;

  try
    {
      a.0 = 123;
      a.1 = 1;
      b.0 = 456;
      b.1 = 5.0e+0;
    }
  finally
    {
      a = {CLOBBER};
      b = {CLOBBER};
    }
}
```

**Comment by bjorn3** [comment]
Just to check: does `(a,)` work? That should give a tuple containing only `a`.

**Comment by philberty** [comment]
> Just to check: does `(a,)` work? That should give a tuple containing only `a`.

in theory it should i will add a test case.

**Comment by philberty** [comment]
Thanks @bjorn3 test case added

**Review by NalaGinrut — APPROVED** [review]
LGTM

**Pull request merged**
