### PR TITLE
[CL] ast dump and refactor

### PR DESCRIPTION
**Pull request by CohenArthur**
@dafaust @philberty if you'd like to review some of the Changelogs :)

### CODE REVIEW

**Review by philberty — APPROVED** [review]
Changelogs ++ LGTM

**Comment by philberty** [comment]
```
 Checking d56418dd1390be731437fc641a3cc5bd624bb47b: FAILED
ERR: missing description of a change: "	* ast/rust-ast-dump.cc (Dump::emit_visibility):"
ERR: missing description of a change: "	(Dump::visit):"
ERR: missing description of a change: "	(Dump::format_function_common):"
```

**Comment by CohenArthur** [comment]
Needs #1787

**Comment by CohenArthur** [comment]
bootstrapped and tested on x86_64 after the merge/update in gcc-patch-dev so I'm confident this is fine. Merging

**Pull request merged**
