### PR TITLE
just for fun

### PR DESCRIPTION
**Pull request by philberty**
I love https://justforfunnoreally.dev/

### CODE REVIEW

**Comment by philberty** [comment]
@seven1m ^^ :D

**Comment by seven1m** [comment]
Nice! (Though somehow it failed the build 😂)

**Comment by CohenArthur** [comment]
> Nice! (Though somehow it failed the build joy)

Yeaaaaaah that's on me haha. Will be fixed soon :) The PR is still going

**Review by CohenArthur — APPROVED** [review]

**Pull request merged**
