### PR TITLE
Implement PhantomData

### LINKED ISSUE #1127: Implement PhantomData
This is the full definition:

```rust
#[lang = "phantom_data"]
pub struct PhantomData<T: ?Sized>;
```

`PhantomData` is a ZST, but in all other aspects it behaves as if it contains a value of type `T`. For example wrt to variance. It also counts as a use of a generic parameter and thus allows disabling the error that generic parameters need to be used.

### PR DESCRIPTION
**Pull request by tamaroning**
Fixes #1127 

Added `phantom_data` lang item

### CODE REVIEW

**Comment by CohenArthur** [comment]
@flip1995 @bjorn3 from what I can gather looking at `rustc`, `PhantomData` seems to only have an impact during lints, which was also my understanding regarding the type. Is there anything I'm missing that `rustc` does around that type?

**Review by CohenArthur — APPROVED** [review]
This looks good to me :) Could you remove the item list from your original message as that will be included in the commit message by our merge bot?

Ping me when that's done and we'll merge it! Thank you for working on this!!

**Comment by tamaroning** [comment]
What do you mean by "the item list"?

**Comment by CohenArthur** [comment]
> What do you mean by "the item list"?

@tamaroning I mean the whole "Here is a checklist to help you with your PR" checklist

**Comment by tamaroning** [comment]
Okey. Done :)

**Comment by CohenArthur** [comment]
Great! Thank you :)

bors r+

**Pull request merged**
