### PR TITLE
Handle gengtype annotations in ```rust-constexpr.cc```

### PR DESCRIPTION
**Pull request by powerboat9**

### CODE REVIEW

**Comment by powerboat9** [comment]
@philberty @CohenArthur I'm not sure why this patch isn't compiling, any ideas?

**Comment by powerboat9** [comment]
Fixed it, it was some sort of type name collision.

**Review by CohenArthur — COMMENTED** [review]
I don't know if that is really needed, I'm wondering if this isn't a remnant of the Go implementation that we ported over a long time ago. We don't use the garbage collecting routines anywhere else in the compiler

**Comment by powerboat9** [comment]
It looks like it might be rather important for constant evaulation

**Review by philberty — APPROVED** [review]
LGTM nice one this stuff is a pain I tried to get it working last year but now I realise yes we needed the using namespace that you found.

Nice work

**Pull request merged**
