### PR TITLE
Remove ```Gcc_backend```

### PR DESCRIPTION
**Pull request by powerboat9**

### CODE REVIEW

**Comment by powerboat9** [comment]
Looks like this can't be split off just yet, converting to draft

**Comment by CohenArthur** [comment]
@powerboat9 is that ready for reviewing? does it depend on anything?

**Review by CohenArthur — APPROVED** [review]
This is good. I think eventually we'll rename `Gcc_backend` to `Backend`, since we no longer have multiple backends (we never had, but the class hierarchy was ready for it!)

**Comment by powerboat9** [comment]
Rethinking this pull request, can you remove it from the merge queue?

**Comment by powerboat9** [comment]
Depends on #2606

**Review by CohenArthur — APPROVED** [review]
Nice :)

**Pull request merged**
