### PR TITLE
hir: Improve pattern bindings handling in closure parameters

### PR DESCRIPTION
**Pull request by goar5670**
Addresses #1807

### CODE REVIEW

**Review by philberty — APPROVED** [review]
LGTM but i am not 10% this fixes https://github.com/Rust-GCC/gccrs/issues/1807 as it seemed to be a parser issue this is applying the pattern logic properly to closures which is good and adds new test cases.

**Comment by philberty** [comment]
This is good to merge if you can confirm what happens when you test this PR with #1807 and we can go from there.

**Comment by goar5670** [comment]
It doesn't completely fix it yet, but the issue is not with reference patterns anymore (or parsing for that matter). It results in an ICE. I think it has something to do with the `&` before the closure pipe or the b'0'.

**Comment by goar5670** [comment]
The way I see it, we have 2 choices. Close 1807 and open a new issue for the new behaviour. Or just leave it open and change the description to 'Addresses' instead of  'Fixes'

**Comment by goar5670** [comment]
> In this case, you should change your description to Addresses and add a comment showing the ICE on the issue. Which can be fixed later on.

Ok done 👍

**Pull request merged**
