### PR TITLE
Unify HIR::IfExprConseqIf{,Let} into HIR::IfExprConseqElse

### PR DESCRIPTION
**Pull request by powerboat9**
This should simplify 'if' expression handling to match simplifications to 'if let' expression handling in order to simplify 'if let' lowering.

### CODE REVIEW

**Comment by powerboat9** [comment]
https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/enum.ExprKind.html#variant.If

rustc does something similar, so these changes shouldn't impair future feature development.

**Comment by powerboat9** [comment]
yak shaving

**Review by CohenArthur — APPROVED** [review]
Thanks :) I think having our HIR being simpler than our AST where it makes sense is nice.

**Review by philberty — APPROVED** [review]
LGTM... YAK shaved...

**Pull request merged**
