### PR TITLE
fix typo in README.md

### PR DESCRIPTION
**Pull request by seeekr**

### CODE REVIEW

**Comment by philberty** [comment]
Thanks for the PR i am going to leave it open to see if we can fix the greetings bot

**Review by philberty — APPROVED** [review]

**Comment by vladdoster** [comment]
@seeekr, @philberty  This is fixed in a single, more encompassing PR #142

**Comment by vladdoster** [comment]
@philberty I figured out the issue with the `Greetings` bot, see PR #142

**Comment by philberty** [comment]
Thanks again for the PR though this has been fixed in other PRs

**Pull request closed without merging**
