### PR TITLE
Ast dump unit struct

### PR DESCRIPTION
**Pull request by jdupak**
Adds dump for unit struct

Depends on #1624

### CODE REVIEW

**Comment by jdupak** [comment]
I could use some help with the failed tests. I am not really sure what it means.

**Comment by philberty** [comment]
You are getting a failure on:

```
FAIL: rust/link/trait_import_0.rs   -O0  (test for excess errors)
Excess errors:
rust1: error: generic param redefined multiple times
rust1: error: was defined here
```

Do a dump of the AST of that file and it should show whats going on. We don't really have location info setup for imports hence the empty errors here.

**Review by CohenArthur — APPROVED** [review]
Looks good to me :) We will merge #1624 first and then could you please rebase this PR on master? Thank you!

**Comment by jdupak** [comment]
Yes, that is the plan.

**Comment by jdupak** [comment]
@CohenArthur rebase done

**Review by CohenArthur — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
