### PR TITLE
remove ast/clone-test.h

### PR DESCRIPTION
**Pull request by humancalico**
Signed-off-by: Akshat Agarwal <humancalico@disroot.org>

Fixes: #99

### CODE REVIEW

**Comment by philberty** [comment]
As this is a removal of code I think its ok. But if you add code you will need to get copyright assignment for GCC.

**Review by philberty — APPROVED** [review]

**Comment by humancalico** [comment]
> As this is a removal of code I think its ok. But if you add code you will need to get copyright assignment for GCC.

@philberty How do I get the relevant forms?

**Comment by philberty** [comment]
> > As this is a removal of code I think its ok. But if you add code you will need to get copyright assignment for GCC.
> 
> @philberty How do I get the relevant forms?

https://gcc.gnu.org/contribute.html

You need to mail the GCC mailing about it

**Review by SimplyTheOther — APPROVED** [review]
PR looks great.

**Pull request merged**
