### PR TITLE
mark live symbol in if expr family except if let expr

### PR DESCRIPTION
**Pull request by thomasyonug**
mark live symbol in if expr family except if let expr

### CODE REVIEW

**Review by philberty — APPROVED** [review]
What about TupleStructs i am not sure if I have seen an example with that.

**Comment by thomasyonug** [comment]
> What about TupleStructs i am not sure if I have seen an example with that.

Yeah, this is a complicated one. I'll implement it soon.

**Comment by philberty** [comment]
> > What about TupleStructs i am not sure if I have seen an example with that.
> 
> Yeah, this is a complicated one. I'll implement it soon.

Let me know if you need help with it @thomasyonug I think I see how to go about it with your other ADT example.

**Comment by thomasyonug** [comment]
> > > What about TupleStructs i am not sure if I have seen an example with that.
> 
> > 
> 
> > Yeah, this is a complicated one. I'll implement it soon.
> 
> 
> 
> Let me know if you need help with it @thomasyonug I think I see how to go about it with your other ADT example.

Thanks. You are right, it's kind of similar, i'm considering how to abstracting some common function to help impl both of tuple struct and struct struct.

**Pull request merged**
