### PR TITLE
Char type

### PR DESCRIPTION
**Pull request by philberty**
Add char type
    
    This might need changes in the Lexer to allow for wchar_t to be preserved.
    
    Addresses #85

### CODE REVIEW

**Review by SimplyTheOther — APPROVED** [review]
PR looks good. I'm a little concerned about "slicing" of the character (since the value is derived from the first byte of the string only) in rust-compile-expr.h, but I imagine this just needs a method call to fix (e.g. encode string to UTF-32 with a method call or something).

**Comment by bjorn3** [comment]
`wchar_t` may be a 16 bit number on some systems, right? A rust `char` is a 32 bit number where every value outside of the range of valid unicode codepoints is invalid and transmuting such an invalid value to `char` is UB.

**Comment by philberty** [comment]
Yep, i think it needs some work to fix the slicing of the character but the GIMPLE tree is a 32 bit unsigned so the backend should be correct at least. I will raise an issue out of this PR for that part.

**Comment by philberty** [comment]
I've raised https://github.com/Rust-GCC/gccrs/issues/233

**Pull request merged**
