### PR TITLE
Added better GroupedPattern support

### PR DESCRIPTION
**Pull request by powerboat9**
Signed-off-by: Owen Avery <powerboat9.gamer@gmail.com>

- \[X] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[X] Read contributing guidlines
- \[X] `make check-rust` passes locally
- \[X] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`
---

Adds better support for GroupedPattern.

### CODE REVIEW

**Comment by powerboat9** [comment]
Taken out of #1719

**Review by CohenArthur — COMMENTED** [review]
This looks good to me, but it's missing a testcase or two :) I want Philip to review that code as I'm not too familiar with it yet however

**Review by philberty — CHANGES_REQUESTED** [review]
The code here looks good to me but I would like you to rebase your changes ontop of #1730 as we will merge that first.

Then I think this PR should be several commits:

1. Update name-resoluton to support GroupedPattern's
2. Add HIR lowering for grouped patterns
3. Add type-resolution for grouped patterns
4. Add missing visitors for grouped patterns in code-generation

Once all of these commits are in then we will be able to see whats remaining to get grouped patterns working and add the relevant test-cases.

Good work!

**Comment by powerboat9** [comment]
Implemented changes, and thank you

**Comment by powerboat9** [comment]
Still have to add those, just compilation checks? Is there any documentation for the testsuite system?

**Comment by CohenArthur** [comment]
> Still have to add those, just compilation checks? Is there any documentation for the testsuite system?

I would suggest looking at previous PRs which add such tests, such as https://github.com/Rust-GCC/gccrs/pull/1709 or #1711. I think one compilation test would be good, + at least one execution test to make sure the value you extract are the proper ones. Once you add a test I'll re-review and we can see together how to improve the testcase if it's not good enough, but it should be fine :)

**Comment by powerboat9** [comment]
It looks like these changes depend on CompilePatternLet from #1719

**Comment by philberty** [comment]
@powerboat9 I am not sure what the order or state of these PR's. So far we merged https://github.com/Rust-GCC/gccrs/commit/dc31146d6392c620a31b0f3e3625224ca4afb3cd and https://github.com/Rust-GCC/gccrs/commit/97c1308bec6bc149b9295b882b7261ca8f3df048

I think the next PR to go should be the name resolver piece then the parts in HIR lowering is two nice PR's

**Comment by powerboat9** [comment]
This has been broken up into multiple pull requests now, so we can close this one.

**Pull request closed without merging**
