### PR TITLE
Move ast collector template implementation to header file

### PR DESCRIPTION
**Pull request by SainiAditya1**
Thank you for making Rust GCC better!

If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.

Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

### CODE REVIEW

**Comment by P-E-P** [comment]
@SainiAditya1 do you need some help with resolving the two remaining problems in the CI ?

**Comment by SainiAditya1** [comment]
@P-E-P yes I need help to resolve this.

**Comment by P-E-P** [comment]
> @P-E-P yes I need help to resolve this.

Sorry for the delay @SainiAditya1 , I was away.

I will assume you know almost nothing in order to ensure you understand every bit of this. Do not take it too personally.

There are two steps failing in the CI:
- `Clang Format Lint / clang-format`
- `GNU Commit Format Checker / check-changelogs`

Those steps are not related, let's split the problem in half and fix those separately.

# Clang Format Lint / clang-format

[`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) is a tool from LLVM, it mainly parse some code and then pretty print it. Different sets of rule can be defined for the pretty printer, those rules are commonly called a "coding style". Clang-format has some builtin sets of rules that can be accessed using the `--style` CLI argument but anyone can use it's own set of rules using a custom file called `.clang-format`.

I've seen you've pretty much figured that out already, you attempted to fix it manually in commit [e291784](https://github.com/Rust-GCC/gccrs/pull/2346/commits/e2917840dc4b0a514e458dff5c23d0767062c97b). While fixing those manually works, it is much faster to uses a script, or even better, configure your editor to format your code on save. It is less error prone and  tedious.

GCC has it's own set of rules, those rules can be found in the `contrib` directory at the root of the project. You may copy this file under a new name in order for it to be recognized by the `clang-format` tool.

```
# From the root of the project
cp contrib/clang-format .clang-format
```

Do not fear creating a new file in the project directory, the `.gitignore` file is already configured so git ignores a file named `.clang-format` at the root of the project [here](https://github.com/Rust-GCC/gccrs/blob/master/.gitignore#L42).

You will then require `clang-format` version 10, the set of rules that define the coding style has changed a bit since hence why the project requires an older version.

You may then either configure your editor to use clang-format or format those files yourself using the following command:

```
clang-format -i XXXX
```

With `XXXX` being the path to the file you modified. Ensure you call `clang-format` from a directory belonging to the project, otherwise the tool won't be able to find the `.clang-format` you copied earlier.

# GNU Commit Format Checker / check-changelogs

All commits shall compile and pass the tests. All commits from this github repository are sent to the official GNU GCC mailing list, this means we should respect a proper format. Every commit message should contain a title, a message as well as a changelog.

Most of your commit messages contain a title but no description and no changelog. I suspect this is because you're using the `-m` argument of the `git commit` command.

In order to generate a changelog template you may use a git hook. This hook already exist and can be installed using the `contrib/gcc-git-customization.sh` script. Once installed, you'll simply have to execute `git gcc-commit-mklog` instead of `git commit`. Note that this hook does not insert any DCO (developper certificate of origin, the "Signed-off by" thing) in your commit message. You may add it after commiting using `git commit --amend -s`.

# Third problem

There is an underlying problem not directly showing up in the CI with your commits. When I said earlier that all commits get sent to the mailing list and should respect a given format, I meant **ALL** commits. This means your merge commits would also be sent there (265731e4150d8132e922ed4a43dbbf46911887fb, e2917840dc4b0a514e458dff5c23d0767062c97b and 27e8545df8a42df8330fb1d0e89dabbf42a5fd9f). We use rebase in order to avoid merge commits. Merge commits are empty commits with multiple parents that exist to represent a merge. Those create some noise, make the history non-linear make therefore harder to deal with.

One of your merge commit is not empty (27e8545df8a42df8330fb1d0e89dabbf42a5fd9f). I suggest that you squash it with 22a269a2260208e844dc11bb257919572483a836 and delete the others so your PR would only have one clean commit.

To do so you need to go to your user's master branch. You will then have to rebase. While looking at the history, I have seen that those commits all come from the `origin/master` as well as your `master`. This is probably because your default pull strategy is merge. You may change this temporarily by using `git pull --rebase` everytime you want to pull some change, or fix it indefinitely by changing the default pull configuration in git:
```
git config --global pull.rebase true
``` 

Hopefully this is clearer. I'm almost sure I missed many points, feel free to ask more questions.

**Comment by MahadMuhammad** [comment]
Hi @SainiAditya1, @P-E-P has done a great job in explaning the issue of your PR. You PR was great :) But there are some CI issues, which we have to fix. I found myself fighting with these CI issues. Therefore, it's worth mentioning the fixes that I use, hope you found it helpful too :DD

If you see the checks which are failing, there are:
- [x] Merge Commits
- [x] Clang Format Lint / clang-format
- [x]  GNU Commit Format Checker / check-changelogs

---
## Merge Commit Issue:
@P-E-P has explained this issue well. But if go to https://github.com/Rust-GCC/gccrs/pull/2346/commits . You can see that there are indeed merge commits


 commits

-  For fixing this, you can follow the solution of @P-E-P, or you can use my solution.
```bash
git reset --hard HEAD~4
git reset --soft  HEAD~1
# These comments are for explanation:


# ➜  gccrs git:(Aditiya) git reset --hard HEAD~4
# HEAD is now at 22a269a2260 Move ast collector template implementation to header file
# ➜  gccrs git:(Aditiya) git reset --soft  HEAD~1



# ➜  gccrs git:(Aditiya) ✗ git status              
# On branch Aditiya
# Your branch is behind 'Aditiya/master' by 97 commits, and can be fast-forwarded.
#   (use "git pull" to update your local branch)
# 
# Changes to be committed:
#   (use "git restore --staged <file>..." to unstage)
# 	modified:   gcc/rust/ast/rust-ast-collector.cc
# 	modified:   gcc/rust/ast/rust-ast-collector.h
# 
```

---
## Clang formating issues:
- GCCRS follows the specfic coding format to keep the code format consistent. For this you have to use `clang-format10`.
- On ubuntu 22.04, unfortunatley, I tried downloading clang-format10 from ubuntu main / universe repositories. But, it didn't find that.
- You can download the `clang-format10` binary from [`here`](https://github.com/DoozyX/clang-format-lint-action/blob/master/clang-format/clang-format10)
- Now, run this command to give executable premission to `clang-format10` . You can place this file to the parent of your gccrs folder. So, you can use this like ../clang-format10. Or Alternatively, you can move this file to bin of your linux distro (if you are using linux)
```bash
chmod +x clang-format10
```
Now, you have to run this onto your modified files, in your case, you have to use
```bash
# clang-format10 -i <relative or absolute location of your file>
# If you placed clang-format10 in the parent directory of gccrs local folder,
# And if your in gccrs folder / directory, then you can use
../clang-format10 -i gcc/rust/ast/rust-ast-collector.cc
../clang-format10 -i gcc/rust/ast/rust-ast-collector.h  
# Here, -i is the inplace flag
```

---

### Now, commit format checker issue:
- For keep tracking the changes made in each change gcc uses change logs, to easily view the bird's eye view of the changes in the desired commit.
- You can run this command

```bash
git gcc-commit-mklog
# ➜  gccrs git:(Aditiya) ✗ git gcc-commit-mklog

``` 
- After, this you can see the output like this:
```bash
 GNU nano 6.2                                                 /home/mahad/Desktop/mahad/gccrs/.git/COMMIT_EDITMSG *                                                         
<your message>

gcc/rust/ChangeLog:

        * ast/rust-ast-collector.cc (TokenCollector::visit): <your message>
        (TokenCollector::visit_items_joined_by_separator): <your message>
        (TokenCollector::visit_as_line): <your changes>
        (TokenCollector::visit_items_as_lines): <your message>
        (TokenCollector::visit_items_as_block): <your message>
        * ast/rust-ast-collector.h: <your message>

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch Aditiya
# Your branch is behind 'Aditiya/master' by 97 commits, and can be fast-forwarded.
#   (use "git pull" to update your local branch)
#
# Changes to be committed:
#       modified:   gcc/rust/ast/rust-ast-collector.cc
#       modified:   gcc/rust/ast/rust-ast-collector.h
#
```
- This will open a in nano, then just press `ctrl + O`, then `ctrl + enter` and finally `ctrl + X` for saving that file. 

- If `git gcc-commit-mklog` gives you error then you have to first set.
- you can run the `./contrib/gcc-git-customization.sh` script (for this you may have to pip3 or other python git packages installed on your system), which will add some useful `git` commands like `git gcc-commit-mklog`. It works exactly the same as `gcc commit`
- Moreover, if you'd like to run changelogs checks that check locally, you can run `contrib/gcc-changelog/git_check_commit.py upstream/master..HEAD` in your terminal. this will check that all the commits on your branch (`HEAD`) that aren't yet merged (so not yet on `upstream/master`) respect the Changelog format.
- Moreover, One thing I would suggest is not creating PRs from your master branch. Here's a little article with commands to avoid it: https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/ (suggested from @CohenArthur)

- Now, you have to sign that commit, (if you are using `gitkraken`, then `gitkraken` will automatically trim new line from the end, which will again give you CI error, therefore, it is better to handle this task to `git`), you can do it manually but git do this for you automatically. By running
```bash
git commit --amend -s  
```
- Now, you can follow the same steps for saving the file. 
-  After this if you run this check `contrib/gcc-changelog/git_check_commit.py upstream/master..HEAD`, it will give you output like this:
```
➜  gccrs git:(Aditiya) contrib/gcc-changelog/git_check_commit.py
Checking f2e9a6726faa4b67442f0dfa1578ee69cdb10dee: OK
```

---

Now, just push your changes.
```bash
git push -f
```

**Comment by MahadMuhammad** [comment]
Hi @SainiAditya1, just fix this one last issue & you PR will be ready to merge.
If you go to [`#2346-commits`](https://github.com/Rust-GCC/gccrs/pull/2346/commits) . You can see that there are indeed merge commits. There should be only one commit, which has to be properly signed and contain proper changelogs.

image
- You can fix this by rebasing or by moving the head to 22a269a2260208e844dc11bb257919572483a836 commit by using

```bash
# here 5 is because there are 5 merge commits
git reset --hard HEAD~5
```


Then, you can soft reset to remove the commit, but the file you edited remain preserved.

```bash
git reset --soft HEAD~1
```
Then, write the changelog by using this command:
```bash
git gcc-commit-mklog
```
Then finally, sign the commit by this 
```bash
git commit --amend -s  
```
> If you are having problem by setting this command you can refer to this https://gcc.gnu.org/contribute.html#patches


And finally push (force) to the origin

```bash
git push -f
```

You can see examples on how to properly commit your message by using `git log` or you can any of the commit from this [`gccrs-master`](https://github.com/Rust-GCC/gccrs/commits/master)

**Comment by P-E-P** [comment]
As @MahadMuhammad said there are still a few merge commit remaining. I believe rebasing your master against the project's master should help to clean this up.

If you haven't already a remote:

```
git remote add git@github.com:Rust-GCC/gccrs.git upstream # Add the project's "link" to your local repository
git checkout -b gccrs_master -t upstream/master # Create a new branch named gccrs_master
git checkout master
git rebase gccrs_master
```

There will be a conflict, simply open your favorite editor and fix it. Git will tell you which file is affected, in your case that should be `rust-ast-collector.cc`. You will see something like this:
```
<<<<
some code 1
=======
some code 2
>>>>
```

Those code are two diverging versions of the code. Your local code will be (2), upstream code is (1). In your situation you have to propagate the changes shown in (1) into your header changes, then delete the `<<<<`, `====` and `>>>>` lines.

```
git add gcc/rust/ast/rust-ast-collector.cc
git rebase --continue
```

Done! Your master is finally up to date. You will then have to squash your two remaining commits into one, add a proper changelog and we will merge those changes.

**Comment by SainiAditya1** [comment]
I am creating a new PR for these changes.

**Pull request closed without merging**
