### PR TITLE
Desugar HIR use and extern crate delcarations

### PR DESCRIPTION
**Pull request by philberty**
These declarations don't have any meaning in the HIR as these statements
are used during name resolution which contain AST::SimplePaths which can
be fully resolved at that stage.

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
+0, -637: The best kind of pull request :DDD LGTM!

**Comment by bjorn3** [comment]
`pub use` still has a meaning, right? It needs to be included in the crate metadata.

**Comment by philberty** [comment]
Darn thats a good point @bjorn3 i will look at this again in a few weeks.

**Comment by philberty** [comment]
I'm going to close this PR and just desugar the ExternBlock out since it doesnt seem to have any effect

**Pull request closed without merging**
