### PR TITLE
[upstream] [2024-02-20] Prepare commits

### PR DESCRIPTION
**Pull request by CohenArthur**
the bot being french, it is on strike for the time being so I'm uploading commits in its stead

### CODE REVIEW

**Comment by CohenArthur** [comment]
the real reason is that we really, really need to merge upstream into us quickly - there are simple cherry-pick conflicts like the commit updating Copyright years that didn't make it through correctly so I had to create that branch manually. should not be an issue next week

**Comment by CohenArthur** [comment]
All commits build, running the tests + 1 last bootstrap build and I'll push upstream

**Comment by dkm** [comment]
> All commits build, running the tests + 1 last bootstrap build and I'll push upstream

Don't you need to add my latest powi fix in there... Probably even fixup! the powi original change in b9f98ac? I guess every 32-bits testsuite run will fail after this faulty powi declaration (my fault, sorry about that).

**Comment by CohenArthur** [comment]
ah yes, I must have created the branch before your fix was actually merged. I'm fine with doing a fixup

**Comment by CohenArthur** [comment]
but we got no reports from any of the 32 bits builders I believe... weird

**Comment by dkm** [comment]
> but we got no reports from any of the 32 bits builders I believe... weird

probably because the (latent) issue only triggers with some upstream change... Do we have some CI that test 32-bits with both my incorrect powi change applied on recent upstream base?

**Comment by CohenArthur** [comment]
I don't know why the CI isn't triggering for this PR... I need to have a look. anyway, I can check manually this time

**Comment by CohenArthur** [comment]
```Running target unix/-m32
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/config/default.exp as tool-and-target-specific interface file.
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/compile/compile.exp ...
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/compile/torture/compile.exp ...
FAIL: rust/compile/torture/intrinsics-math.rs   -O1  (internal compiler error: Segmentation fault)
FAIL: rust/compile/torture/intrinsics-math.rs   -O1  (test for excess errors)
FAIL: rust/compile/torture/intrinsics-math.rs   -O2  (internal compiler error: Segmentation fault)
FAIL: rust/compile/torture/intrinsics-math.rs   -O2  (test for excess errors)
FAIL: rust/compile/torture/intrinsics-math.rs   -O3 -g  (internal compiler error: Segmentation fault)
FAIL: rust/compile/torture/intrinsics-math.rs   -O3 -g  (test for excess errors)
FAIL: rust/compile/torture/intrinsics-math.rs   -Os  (internal compiler error: Segmentation fault)
FAIL: rust/compile/torture/intrinsics-math.rs   -Os  (test for excess errors)
FAIL: rust/compile/torture/intrinsics-math.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (internal compiler error: Segmentation fault)
FAIL: rust/compile/torture/intrinsics-math.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (test for excess errors)
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/compile/xfail/xfail.exp ...
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/debug/debug.exp ...
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/execute/torture/execute.exp ...
Running /home/arthur/Git/rust-gcc/gccrs-patches/gcc/testsuite/rust/link/link.exp ...

		=== rust Summary ===

# of expected passes		8397
# of unexpected failures	10
# of expected failures		69
# of unsupported tests		1
```

**Comment by CohenArthur** [comment]
(that's without your latest patch)

**Comment by CohenArthur** [comment]
(which is going to break the bot again next week lol because it does not like empty commits at the moment)

**Comment by CohenArthur** [comment]
upstreamed, emails sent

**Comment by CohenArthur** [comment]
j

**Pull request closed without merging**
