### PR TITLE
Create base class ```AssociatedItem```

### PR DESCRIPTION
**Pull request by powerboat9**
Taken from #2670

### CODE REVIEW

**Comment by dkm** [comment]
Is "deconstructor" a reference to something precise, or is it supposed to read "destructor"?

**Comment by powerboat9** [comment]
It refers to [member functions which are called when the lifetime of an object ends](https://en.cppreference.com/w/cpp/language/destructor) :P

**Comment by dkm** [comment]
> It refers to [member functions which are called when the lifetime of an object ends](https://en.cppreference.com/w/cpp/language/destructor) :P

Ok, so destructor, not deconstructor as you had in the commit log :) I was wondering if this was yet-another C++ concept I didn't know :)

**Review by philberty — CHANGES_REQUESTED** [review]
I can see this being useful can you do the same for the HIR?

Need @CohenArthur sign off here too for this one. I like this idea

**Comment by powerboat9** [comment]
I'd probably want to modify the HIR in another pull request -- it looks like the HIR representation of associated items is already slightly different from the AST representation

**Review by CohenArthur — APPROVED** [review]
looks great! thank you :D I like these changes

**Pull request merged**
