### PR TITLE
fixup: Fix bootstrap build

### LINKED ISSUE #2181: Bootstrap build failure
Bootstrap build is failing on master since afcde5f8175 with the following error:
```
make[3]: *** No rule to make target '../libgrust/libproc_macro/libproc_macro.a', needed by 'crab1'.  Stop.
```

Failing [action](https://github.com/Rust-GCC/gccrs/actions/runs/4869971300/jobs/8685132648)

### PR DESCRIPTION
**Pull request by P-E-P**
The bootstrap was failing due to a missing target which was not available during the bootstrap.

ChangeLog:

	* Makefile.def: Add libgrust target to bootstrap.
	* Makefile.in: Regenerate.

Fixes #2181

### CODE REVIEW

**Comment by P-E-P** [comment]
@CohenArthur This should be merged and then fixed up with  while upstreaming on https://github.com/Rust-GCC/gccrs/commit/afcde5f8175f294baf89141bcc24b8a6ba6499fd.

@tschwinge Is this the correct fix ? I found no documentation around `bootstrap`, I had to solely rely on the `makefile.def` in an attempt to understand what should be fixed and I may have missed something.

**Comment by tschwinge** [comment]
Looking into this.

I wonder, don't we also need `dependencies = { module=all-gcc; on=all-libgrust; hard=true; };`?

**Comment by P-E-P** [comment]
> I wonder, don't we also need `dependencies = { module=all-gcc; on=all-libgrust; hard=true; };`?

Won't this will compile libgrust even when the rust language is disabled ?

**Comment by tschwinge** [comment]
This feels a bit weird what we're doing here...  ;-|

One step back.

So this relates to #2153 "Modularize libproc macro" commit afcde5f8175f294baf89141bcc24b8a6ba6499fd "libproc_macro: Build statically".  Does this `libgrust/libproc_macro` code need to be _(a)_ (statically) linked into the compiler only vs. also _(b)_ needs to be available in another way (target library)?  For linking into the compiler, should it simply be built only (case _(a)_) vs. additionally (case _(b)_) as part of the Rust front end build process?  (Even if the sources live in `libgrust/libproc_macro/` to cater for case _(b)_?

**Comment by CohenArthur** [comment]
Merging this and then we'll have a look at #2242

**Pull request merged**
