### PR TITLE
Remove target hooks changes

### PR DESCRIPTION
**Pull request by philberty**
This reverts the unnecessary changes we have made to GCC
so that merging from upstream should be simplified. This is
also making writing the patches for GCC simpler.

### CODE REVIEW

**Comment by philberty** [comment]
hmm i didnt get these failures locally I must try and clean build dir for this locally.

**Comment by philberty** [comment]
The expected warnings needed to be updated post the reset of the genhooks.cc

**Review by CohenArthur — APPROVED** [review]
Ah :D Good catch on the warnings

**Pull request merged**
