### PR TITLE
Marking live symbols in tuple expr, array expr, grouped expr, type cast expr, lazy boolean expr.

### PR DESCRIPTION
**Pull request by thomasyonug**
Marking live symbols in tuple expr, array expr, grouped expr, type cast expr, lazy boolean expr.

### CODE REVIEW

**Comment by thomasyonug** [comment]
These commits are kind of similar, maybe squash to one commit maybe more clear?

**Comment by philberty** [comment]
@thomasyonug I think this is fine :D. Also I know alot of features are mising in the compiler so if you run into issues with that let me know, we can likely leave it to be filled out later on at some point.

**Review by philberty — APPROVED** [review]

**Comment by thomasyonug** [comment]
> @thomasyonug I think this is fine :D. Also I know alot of features are mising in the compiler so if you run into issues with that let me know, we can likely leave it to be filled out later on at some point.

Sure, I collected some unimplemented features in my kanban. 
Most of them are recorded in that feature doc, and the missed others I will create corresponding issues. :)

**Pull request merged**
