### PR TITLE
include memmodel.h above tm_p.h in order to build success in SPARC64

### LINKED ISSUE #450: Build error in Sparc64
``` bash
In file included from ./tm_p.h:4,
                 from ../../gcc/config/sparc/sparc-rust.c:22:
../../gcc/config/sparc/sparc-protos.h:45:47: error: use of enum 'memmodel' without previous declaration
   45 | extern void sparc_emit_membar_for_model (enum memmodel, int, int);
      |                                               ^~~~~~~~
make[2]: *** [../../gcc/config/sparc/t-sparc:33: sparc-rust.o] Error 1
make[2]: *** Waiting for unfinished jobs....
../../gcc/rust/lex/rust-token.cc: In member function 'const string& Rust::Token::get_str() const':
../../gcc/rust/lex/rust-token.cc:126:40: warning: unquoted sequence of 2 consecutive punctuation characters '',' in format [-Wformat-diag]
  126 |        "attempted to get string for '%s', which has no string. "
      |                                        ^~
../../gcc/rust/lex/rust-token.cc:127:39: warning: spurious trailing punctuation sequence '.' in format [-Wformat-diag]
  127 |        "returning empty string instead.",
      |                                       ^
../../gcc/rust/lex/rust-token.cc:126:37: warning: unterminated quote character ''' in format [-Wformat-diag]
  126 |        "attempted to get string for '%s', which has no string. "
      |                                     ^
../../gcc/rust/lex/rust-lex.cc: In member function 'Rust::TokenPtr Rust::Lexer::parse_byte_char(Location)':
../../gcc/rust/lex/rust-lex.cc:1321:21: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1321 |       if (byte_char > 127)
      |           ~~~~~~~~~~^~~~~
../../gcc/rust/lex/rust-lex.cc:1324:11: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1324 |     "byte char %<%c%> out of range", byte_char);
      |           ^~~~
../../gcc/rust/lex/rust-lex.cc:1332:59: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1332 |    rust_error_at (get_current_location (), "unclosed byte char");
      |                                                           ^~~~
../../gcc/rust/lex/rust-lex.cc:1350:59: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1350 |    rust_error_at (get_current_location (), "unclosed byte char");
      |                                                           ^~~~
../../gcc/rust/lex/rust-lex.cc:1360:43: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1360 |        "no character inside %<%> for byte char");
      |                                           ^~~~
../../gcc/rust/lex/rust-lex.cc: In member function 'Rust::TokenPtr Rust::Lexer::parse_byte_string(Location)':
../../gcc/rust/lex/rust-lex.cc:1396:20: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1396 |    if (output_char > 127)
      |        ~~~~~~~~~~~~^~~~~
../../gcc/rust/lex/rust-lex.cc:1399:10: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1399 |         "char %<%c%> in byte string out of range",
      |          ^~~~
../../gcc/rust/lex/rust-lex.cc: In member function 'Rust::TokenPtr Rust::Lexer::parse_decimal_int_or_float(Location)':
../../gcc/rust/lex/rust-lex.cc:1883:34: warning: unquoted keyword 'float' in format [-Wformat-diag]
 1883 |     "invalid type suffix %qs for float literal",
      |                                  ^~~~~
../../gcc/rust/lex/rust-lex.cc:1932:34: warning: unquoted keyword 'float' in format [-Wformat-diag]
 1932 |     "invalid type suffix %qs for float literal",
      |                                  ^~~~~
../../gcc/rust/lex/rust-lex.cc: In member function 'Rust::TokenPtr Rust::Lexer::parse_char_or_lifetime(Location)':
../../gcc/rust/lex/rust-lex.cc:1978:53: warning: unquoted keyword 'char' in format [-Wformat-diag]
 1978 |    rust_error_at (get_current_location (), "unended char literal");
      |                                                     ^~~~
../../gcc/rust/lex/rust-lex.cc:2035:47: warning: unquoted keyword 'char' in format [-Wformat-diag]
 2035 |      "expected %' after character constant in char literal");
      |                                               ^~~~
In file included from ./tm_p.h:4,
                 from ../../gcc/rust/rust-session-manager.cc:29:
../../gcc/config/sparc/sparc-protos.h:45:47: error: use of enum 'memmodel' without previous declaration
   45 | extern void sparc_emit_membar_for_model (enum memmodel, int, int);
      |                                               ^~~~~~~~

```

It seems like we forgot to include "memmodel.h" before "tm_p.h".

### PR DESCRIPTION
**Pull request by thomasyonug**
Fixes #450

Include "memmodel.h" above "tm_p.h" in order to build success in SPARC64

I had built rust1 in SPARC64 but got some fail tests. It's another independent issue I think.
```
Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using /home/thomasyoung/gccrs/gcc/testsuite/config/default.exp as tool-and-target-specific interface file.
Running /home/thomasyoung/gccrs/gcc/testsuite/rust.test/compile/compile.exp ...
FAIL: rust.test/compile/generics11.rs   -O0  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O0  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -O1  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O1  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -O2  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O2  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -O3 -g  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O3 -g  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -Os  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -Os  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (test for excess errors)
FAIL: rust.test/compile/generics11.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (internal compiler error)
FAIL: rust.test/compile/generics11.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O0  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O0   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O0  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O1  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O1   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O1  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O2  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O2   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O2  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O3 -g  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O3 -g   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O3 -g  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -Os  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -Os   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -Os  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (test for excess errors)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (internal compiler error)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects   (test for warnings, line 4)
FAIL: rust.test/compile/struct_init_2.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O0  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O0   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O0  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O1  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O1   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O1  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O2  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O2   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O2  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O3 -g  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O3 -g   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O3 -g  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -Os  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -Os   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -Os  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (test for excess errors)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (internal compiler error)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects   (test for warnings, line 9)
FAIL: rust.test/compile/struct_init_3.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O0  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O0   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O0  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O1  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O1   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O1  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O2  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O2   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O2  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O3 -g  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O3 -g   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O3 -g  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -Os  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -Os   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -Os  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fno-use-linker-plugin -flto-partition=none  (test for excess errors)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (internal compiler error)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects   (test for warnings, line 5)
FAIL: rust.test/compile/struct_init_8.rs   -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects  (test for excess errors)
Running /home/thomasyoung/gccrs/gcc/testsuite/rust.test/execute/execute.exp ...
Running /home/thomasyoung/gccrs/gcc/testsuite/rust.test/unsupported/unsupported.exp ...
Running /home/thomasyoung/gccrs/gcc/testsuite/rust.test/xfail_compile/xfail_compile.exp ...
FAIL: rust.test/xfail_compile/struct_init1.rs (internal compiler error)
FAIL: rust.test/xfail_compile/struct_init1.rs  (test for errors, line 7)
FAIL: rust.test/xfail_compile/struct_init1.rs  (test for errors, line 7)
FAIL: rust.test/xfail_compile/struct_init1.rs (test for excess errors)

		=== rust Summary ===

# of expected passes		2284
# of unexpected failures	81
# of expected failures		26
```

### CODE REVIEW

**Comment by philberty** [comment]
Nice work!

**Review by philberty — APPROVED** [review]

**Comment by philberty** [comment]
Looks as though bors has crashed, or so the dashboard says.

**Comment by philberty** [comment]
Its actually merged it too

**Comment by thomasyonug** [comment]
LOL, poor little bot. Should I just close this pr?

**Comment by philberty** [comment]
> LOL, poor little bot. Should I just close this pr?

Yeah, go ahead just double check your code was merged into master correctly first.

**Pull request closed without merging**
