### PR TITLE
Moved Functions

### PR DESCRIPTION
**Pull request by Parthib314**
* Fixes issue #1767 

**Moved all the methods from `rust-gcc-diagnostics.cc` to `rust-diagnostics.cc`**
**Deleted the `rust-gcc-diagnostics.cc` file**
**Update the `MakeLang.in` file**

Signed-off-by: Parthib <parthibdutta02@gmail.com>

### CODE REVIEW

**Comment by powerboat9** [comment]
You have to copy contrib/clang-format to .clang-format for `git clang-format` to use the correct format.

**Comment by powerboat9** [comment]
../../gcc/rust/rust-diagnostics.cc:129:5: error: ‘rust_be_error_at’ was not declared in this scope; did you mean ‘rust_error_at’?
      129 |     rust_be_error_at(Linemap::unknown_location(),
          |     ^~~~~~~~~~~~~~~~
          |     rust_error_at

**Comment by Parthib314** [comment]
Ooops ,I think I've messed it up.

**Comment by Parthib314** [comment]
> You have to copy contrib/clang-format to .clang-format for `git clang-format` to use the correct format.

This time I've done it.
While running the clang-format test locally it says `clang-format-10 --version` command failed to start. So I tried to install it but it says `unable to locate package clang-format-10`. Can I use clang-format instead of clang-format-10. My clang-format version is 14.0

**Comment by CohenArthur** [comment]
> * Fixes issue [Refactor rust-gcc-diagnostics.cc #1767](https://github.com/Rust-GCC/gccrs/issues/1767)

One quick comment: github does not understand that format of "closing comment". So in order to have a PR automatically close an issue when it is merged, you need to write something like:

Fixes #1767 

I think once the clang-format issues are dealt with this PR looks good, but I haven't really reviewed it for now

**Comment by Parthib314** [comment]
I am closing this PR because I think I've messed up the `my-patch` branch. I made a new [PR](https://github.com/Rust-GCC/gccrs/pull/1789) regarding the issue.

**Pull request closed without merging**
