### PR TITLE
HIR Visitor refactoring

### LINKED ISSUE #825: HIR Visitor Refactoring
# Background

Our HIR implementation is based off our AST slowly but surely we are cleaning this up to make the HIR much slimer such as no macros and methods are functions, all loops are loop expressions etc.

As part of this bootstrapping from our AST we only have a single Visitor interface that contains abstract methods for every type see: https://github.com/Rust-GCC/gccrs/blob/0024bc2f028369b871a65ceb11b2fddfb0f9c3aa/gcc/rust/hir/tree/rust-hir-visitor.h

The problem here is that when we are working with the full tree of the HIR we are forced to create visitor classes which contain all of the potential types even though the flow of the tree is always:

  Crate -> Items / types -> Stmts/Items/types -> Expressions / types

So even though we have a fully and strongly typed Intermediate representation to work with, we are not getting the full advantages of this yet. The major issue we have is that to avoid having to create overblown classes implementing every node in the graph we have these base classes: https://github.com/Rust-GCC/gccrs/blob/0024bc2f028369b871a65ceb11b2fddfb0f9c3aa/gcc/rust/backend/rust-compile-base.h

Which are starting to make the code quite messy to work with, the other problem is that every method has an empty block default we have cases in the code that do not have implementation such as the recent issue with ReferenceTypes on ImplBlocks such as:

```rust
impl<T> Foo for &T {}
```

This was due to the fact that impl blocks act on any HIR::TypeNoBounds and this visitor was missing an implementation for reference types:

https://github.com/Rust-GCC/gccrs/blob/0024bc2f028369b871a65ceb11b2fddfb0f9c3aa/gcc/rust/resolve/rust-ast-resolve-type.h#L125

Although that example is in the AST it shows how this visitor was missing making it very easy to miss cases in the full IR graph. If we have many smaller visitors we can do away with these base classes and use the C++ compiler to enforce the missing methods through using visitor abstract base classes. This will make it less confusing what methods we need to implement.

Then to take advantage of these new visitors let's focus this on the backend module (this should also be renamed to generic or something but that's a separate issue, backend is a bit of a weird name). If we focus usage of these new HIR visitors on the backend we limit the impact in finding regressions in the type-checking and lint passes until we are happy with this and the backend pass is a simpler case to start with.

https://github.com/Rust-GCC/gccrs/blob/0024bc2f028369b871a65ceb11b2fddfb0f9c3aa/gcc/rust/hir/tree/rust-hir-item.h

This single issue is not the finished goal but the starting point in a journey to make gccrs easier to work with and debug.

## Tasks

- [x] Refactor the existing HIR Visitor to be called HIRFullVisitor as shown here https://github.com/Rust-GCC/gccrs/commit/eb6963324cd48fb4774ad38723562b98e2d9dd28

This visitor will be different to the following visitors in that it will contain a non-abstract base class so that you can choose which methods we wish to override.

### HIRVisItemVisitor

rust-hir-item.h
- [ ] 697:class Module : public VisItem
- [ ] 776:class ExternCrate : public VisItem
- [ ] 1038:class UseDeclaration : public VisItem
- [ ] 1098:class Function : public VisItem, public ImplItem
- [ ] 1257:class TypeAlias : public VisItem, public ImplItem
- [ ] 1371:class Struct : public VisItem
- [ ] 1833:class Enum : public VisItem
- [ ] 1941:class Union : public VisItem
- [ ] 2028:class ConstantItem : public VisItem, public ImplItem
- [ ] 2111:class StaticItem : public VisItem
- [ ] 2503:class Trait : public VisItem
- [ ] 2627:class ImplBlock : public VisItem
- [ ] 3017:class ExternBlock : public VisItem

Every pass in the compiler starts with a top-level Item pass as these are the top-level constructs in the language

###  HIRImplItemisitor

The next step is ImplItems since when walking the graph we end up hitting ImplBlocks early which contains a list of ImplItems so we need to be able to access those:

rust-hir-item.h

- [ ] 1098:class Function : public VisItem, public ImplItem
- [ ] 1257:class TypeAlias : public VisItem, public ImplItem
- [ ] 2028:class ConstantItem : public VisItem, public ImplItem

### HIRTypeVisitor

Next we need to be able to access types in Rust we really have two different kind of type HIR::Type the overall type base class or we have TypeNoBounds. For now as part of this cleanup lets just start with a simple class for all types

rust-hir.h

- [ ] 377:class TypeNoBounds : public Type          // I think these might just be base classes
- [ ] 436:class Lifetime : public TypeParamBound // this is a types but we don't do anything with it

rust-hir-path.h

- [ ] 431:class TypePathSegmentGeneric : public TypePathSegment
- [ ] 566:class TypePathSegmentFunction : public TypePathSegment
- [ ] 611:class TypePath : public TypeNoBounds
- [ ] 845:class QualifiedPathInType : public TypeNoBounds

rust-hir-type.h

- [ ] 33:class TraitBound : public TypeParamBound
- [ ] 86:class ImplTraitType : public Type
- [ ] 145:class TraitObjectType : public Type
- [ ] 213:class ParenthesisedType : public TypeNoBounds
- [ ] 281:class ImplTraitTypeOneBound : public TypeNoBounds // this can probably go away in a future pr by desugaring into ImplTraitType but that's a seperate issue
- [ ] 320:class TupleType : public TypeNoBounds
- [ ] 388:class NeverType : public TypeNoBounds
- [ ] 417:class RawPointerType : public TypeNoBounds
- [ ] 484:class ReferenceType : public TypeNoBounds
- [ ] 559:class ArrayType : public TypeNoBounds
- [ ] 623:class SliceType : public TypeNoBounds
- [ ] 676:class InferredType : public TypeNoBounds
- [ ] 785:class BareFunctionType : public TypeNoBounds

### HIRStmtVisitor

This one is a bit more annoying since Stmts can also contain some Items but let's just handle it like the others

rust-hir-stmt.h

- [ ] 29:class EmptyStmt : public Stmt
- [ ] 54:class LetStmt : public Stmt
- [ ] 134:class ExprStmt : public Stmt
- [ ] 153:class ExprStmtWithoutBlock : public ExprStmt
- [ ] 197:class ExprStmtWithBlock : public ExprStmt

rust-hir.h 
119:class Item : public Stmt

// ^^ this hierarchy is a bit annoying at we may want to change it in the future because of enum-item making it confusing so let's just get it to contain the relevant VisItems for now

- [ ] 697:class Module : public VisItem
- [ ] 776:class ExternCrate : public VisItem
- [ ] 1038:class UseDeclaration : public VisItem
- [ ] 1098:class Function : public VisItem, public ImplItem
- [ ] 1257:class TypeAlias : public VisItem, public ImplItem
- [ ] 1371:class Struct : public VisItem
- [ ] 1833:class Enum : public VisItem
- [ ] 1941:class Union : public VisItem
- [ ] 2028:class ConstantItem : public VisItem, public ImplItem
- [ ] 2111:class StaticItem : public VisItem
- [ ] 2503:class Trait : public VisItem
- [ ] 2627:class ImplBlock : public VisItem
- [ ] 3017:class ExternBlock : public VisItem

This is all because Rust allows for Blocks to contain items functions etc see: https://doc.rust-lang.org/reference/statements.html I wonder are there any limits on statements within blocks the reference does not mention any but maybe we will need someone to double-check this at some point we might be able to remove some things from this such as the extern block's maybe I have never seen those within a rust block expression.

### HIRExpressionVisitor

Finally lets finish this initial refactor with an expression visitor:

- [ ] rust-hir.h
- [ ] 225:class ExprWithoutBlock : public Expr
- [ ] 266:class IdentifierExpr : public ExprWithoutBlock
- [ ] 734:class PathExpr : public ExprWithoutBlock
- [ ] rust-hir-expr.h
- [ ] 32:class ExprWithBlock : public Expr // this is a base class
- [ ] 61:class LiteralExpr : public ExprWithoutBlock
- [ ] 125:class OperatorExpr : public ExprWithoutBlock
- [ ] 744:class GroupedExpr : public ExprWithoutBlock
- [ ] 933:class ArrayExpr : public ExprWithoutBlock
- [ ] 1008:class ArrayIndexExpr : public ExprWithoutBlock
- [ ] 1073:class TupleExpr : public ExprWithoutBlock
- [ ] 1157:class TupleIndexExpr : public ExprWithoutBlock
- [ ] 1228:class StructExpr : public ExprWithoutBlock
- [ ] 1628:class CallExpr : public ExprWithoutBlock
- [ ] 1708:class MethodCallExpr : public ExprWithoutBlock
- [ ] 1796:class FieldAccessExpr : public ExprWithoutBlock
- [ ] 1920:class ClosureExpr : public ExprWithoutBlock
- [ ] 2002:class BlockExpr : public ExprWithBlock
- [ ] 2181:class ContinueExpr : public ExprWithoutBlock
- [ ] 2224:class BreakExpr : public ExprWithoutBlock
- [ ] 2301:class RangeExpr : public ExprWithoutBlock
- [ ] 2609:class ReturnExpr : public ExprWithoutBlock
- [ ] 2677:class UnsafeBlockExpr : public ExprWithBlock
- [ ] 2765:class BaseLoopExpr : public ExprWithBlock
- [ ] 3053:class IfExpr : public ExprWithBlock
- [ ] 3266:class IfLetExpr : public ExprWithBlock
- [ ] 3840:class MatchExpr : public ExprWithBlock
- [ ] 3919:class AwaitExpr : public ExprWithoutBlock
- [ ] 3969:class AsyncBlockExpr : public ExprWithBlock

## TLDR on Tasks:

Let's focus the initial refactor on these 5 new visitors and use them to update the code within the Backend module for now.

- HIRVisItemVisitor
- HIRImplItemisitor
- HIRTypeVisitor
- HIRStmtVisitor
- HIRExpressionVisitor

### PR DESCRIPTION
**Pull request by dkm**
This change split the single HIR visitor in smaller abstract ones:
- Stmt
- VisItem
- Pattern
- ExternalItem
- Impl
- Type
- Expression

Instead of providing a Base class with empty visit() methods, they are kept
abstract to avoid the case where a missing visit() is silently ignored:
implementors must explicitely override all visit.

There is also a FullVisitor that covers all HIR nodes and also provides a Base
class with empty behavior.

fixes #825

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Review by philberty — APPROVED** [review]
I love this its shaping up really well

**Comment by dkm** [comment]
I've created 2 more visitors for ExternalItem and TraitItem. I initially added them in the VisItemVisitor, but all current implementations of this visitor were only overriding EI or TI.
This also shows that nobody cares for only VisItem yet (side effect of being a subclass of Stmt ?). Or maybe some implem of StmtVisitor could be refined as VisItem? I'll check that later.

**Review by philberty — APPROVED** [review]
Thank you so much for persevering through this big refactor it will really help us down the line

**Pull request merged**
