### PR TITLE
Running `clang-format` locally [#242]

### PR DESCRIPTION
**Pull request by tschwinge**
Apparently everyone but me knows how to do that; I'm now documenting it for my
own future use.

### CODE REVIEW

**Review by mathstuf — APPROVED** [review]
Changes look good. Not happy with this way of enforcing formatting, but I'll bring that up elsewhere :) .

**Review by philberty — APPROVED** [review]

**Comment by philberty** [comment]
I think @dkm uses git clang-format is that right?

**Comment by dkm** [comment]
November 5, 2021 1:18 PM, "Philip Herron" ***@***.***> wrote:

> I think @dkm uses git clang-format is that right?
>

Yes, and I also said I would document this... So, let me commit to that and add some more details here. You can still merge that and I'll add more change later this weekend :)

**Comment by tschwinge** [comment]
Yes, that's what @dkm said in <https://github.com/Rust-GCC/gccrs/pull/514#issuecomment-865681557>, <https://github.com/Rust-GCC/gccrs/pull/725#issuecomment-938032551>, for example.

`git clang-format` (as well as the manual-use instructions in GCC `contrib/clang-format`) work on patches; GCC/Rust `.github/workflows/clang-format.yml` (and my new manual-use instructions) works on the actual `gcc/rust/` files.

**Comment by tschwinge** [comment]
And then we also have @philberty's Emacs magic: <https://github.com/Rust-GCC/gccrs/pull/514#issuecomment-865323008>, which may also be worth documenting.

**Comment by tschwinge** [comment]
Relatedly, see also discussion in <https://github.com/Rust-GCC/gccrs/pull/777#issuecomment-961745971> and following, and <https://gcc-rust.zulipchat.com/#narrow/stream/266897-general/topic/clang-format.20strategy>.

**Pull request merged**
