### PR TITLE
Add libstdc++ dependency to libgrust

### LINKED ISSUE #2582: Fix cross compilation
Cross compilation since the addition of `libgrust` is broken because it was not correctly configured to use the c++ standard library.

This lead to #2113 which was not the right fix since we require c++ in libgrust. Discussion continued in #2143.

### PR DESCRIPTION
**Pull request by P-E-P**
Add a libstd++-v3 dependency to libgrust in order to be able to compile it properly when using a crosscompiler. The documentation said it was better to use a soft dependency so here it is. @tschwinge is this correct ? Should I change something else ? Do we need a `lang_env` dependency ?

Related to #2113 

Fixes #2582

### CODE REVIEW

**Review by philberty — APPROVED** [review]
This looks like the right way to do it iirc

**Review by CohenArthur — APPROVED** [review]
LGTM but also I know nothing about how to do that so I'll let @tschwinge handle the PR :D

**Comment by P-E-P** [comment]
> I'm (slowly...) working on getting to the bottom of this -- but still in progress. I think further changes may be necessary here.
> 
> @P-E-P: Are you testing this in a cross-configuration?

No I don't

**Comment by P-E-P** [comment]
I tested a cross compiler and it seems these changes were not sufficient, I'll mark this PR as draft and investigate again.

**Comment by CohenArthur** [comment]
Trying a local bootstrap and will report on the results

**Comment by CohenArthur** [comment]
bootstrap build succeeded @P-E-P!

**Comment by gyrovorbis** [comment]
Whoo! That fixed it for us cross-compiling for the SH arch targeting Dreamcast. Thank you! :)

**Comment by tschwinge** [comment]
Cross-referencing here <https://inbox.sourceware.org/8734xv24dd.fsf@euler.schwinge.homeip.net> "Disable target libgrust if we're not building target libstdc++".

**Pull request merged**
