### PR TITLE
HIR cleanup and refactor

### PR DESCRIPTION
**Pull request by jdupak**
Minor changed done during the borrowck work. Tested after each  commit (but before the last rebase).

### CODE REVIEW

**Comment by dkm** [comment]
Not really sure, but you have 28 commits from various dev with conflicts with master... Looks like your branch is not cleanly rebased onto master?

**Comment by jdupak** [comment]
> Not really sure, but you have 28 commits from various dev with conflicts with master... Looks like your branch is not cleanly rebased onto master?

Yeah, I know. It was based on another PR that was not merged yet. Fixed.

**Review by CohenArthur — APPROVED** [review]
LGTM. nice small changes :)

**Review by P-E-P — APPROVED** [review]
LGTM

**Pull request merged**
