### PR TITLE
[CL] missing commits from after #1705

### PR DESCRIPTION
**Pull request by CohenArthur**
There were 22 commit Changelogs missing which should now be fixed.

### CODE REVIEW

**Comment by CohenArthur** [comment]
How should we deal with 38adbd453ea76814ae8e809b92bdcd6c960dc865 @tschwinge? This isn't really an `Update copyright year` commit since it only concerns `gcc/rust/` files. So should I add a Changelog to it and a `gccrs: ` prefix? What do you think?

**Comment by CohenArthur** [comment]
Also, I don't think [2dd73cf](https://github.com/Rust-GCC/gccrs/pull/1889/commits/2dd73cf151ec8ec1a3ee16cf2cf695bdf321288b) should be in this series... :thinking:

**Comment by CohenArthur** [comment]
> Also, I don't think [2dd73cf](https://github.com/Rust-GCC/gccrs/pull/1889/commits/2dd73cf151ec8ec1a3ee16cf2cf695bdf321288b) should be in this series... thinking

Ah, right. This is because we haven't updated `gcc-patch-dev` yet

**Comment by tschwinge** [comment]
> How should we deal with [38adbd4](https://github.com/Rust-GCC/gccrs/commit/38adbd453ea76814ae8e809b92bdcd6c960dc865) @tschwinge? This isn't really an `Update copyright year` commit since it only concerns `gcc/rust/` files. So should I add a Changelog to it and a `gccrs: ` prefix? What do you think?

Why shouldn't it be just `Update copyright years.` anyway?

But, there's some other problem with that commit: it contains unrelated changes -- how did that happen?  :-O

Ideally, as discussed on IRC yesterday, the individual `Update copyright years.` should (have) be(en) moved into the individual upstreaming commits.  (..., but not sure if any remain, that have not yet been upstreamed.)

**Review by philberty — APPROVED** [review]
LGTM

**Pull request merged**
