### PR TITLE
[upstream] 2024-03-19

### PR DESCRIPTION
**Pull request by CohenArthur**
@gerris-rs didn't like some of the reverts and empty commits (which I'm not sure why they were present actually. a second set of eyes on this would be good :)

### CODE REVIEW

**Comment by tschwinge** [comment]
Something is wrong with the baseline -- as presented here, this includes a lot of commits already present in GCC upstream.

**Comment by tschwinge** [comment]
We can't upstream the _format_parser_ changes until we've sorted out the build system issues that have been raised.

**Comment by tschwinge** [comment]
This appears to be missing my commit 705de6d54ca95b8277a15fe9a2255af6168ae086 "Rust: Make 'tree'-level 'MAIN_NAME_P' work".

**Comment by CohenArthur** [comment]
Closing in favor of #2965

**Pull request closed without merging**
