### PR TITLE
libgrust: Vendor Rust dependencies

### LINKED ISSUE #2882: Locally provide crates that `libgrust` depends on
As of #2822 "Start reusing rustc's format_args parser", we have:

```
[...]
make[3]: Entering directory '[...]/build-gcc/gcc'
cargo build --manifest-path [...]/source-gcc/gcc/../libgrust/libformat_parser/Cargo.toml --release # FIXME: Not always release, right?
    Updating crates.io index
 Downloading crates ...
  Downloaded unicode-xid v0.2.4
  Downloaded libc v0.2.152
   Compiling libc v0.2.152
   Compiling unicode-xid v0.2.4
   Compiling generic_format_parser v0.1.0 ([...]/source-gcc/libgrust/libformat_parser/generic_format_parser)
   Compiling libformat_parser v0.1.0 ([...]/source-gcc/libgrust/libformat_parser)
    Finished release [optimized] target(s) in 2.39s
[...]
```

For different reasons, GCC needs to build without Internet access.  Therefore, need to locally provide crates that `libgrust` depends on, either by importing into `libgrust`, or by new `--with-[...]` `configure` flags and instructions how to download/prepare them externally in a suitable format (source or binary).

### PR DESCRIPTION
**Pull request by CohenArthur**
This commits vendors and locks our dependencies so that our Rust components
do not need internet access to be built anymore. Tested in a docker container
with no network access.

We can think about merging the vendor directory once we have more than one
Rust component, e.g. when we add polonius to the mix.

Fixes #2882

### CODE REVIEW

**Comment by CohenArthur** [comment]
Note that this was simply generated with `cargo vendor`

**Comment by tschwinge** [comment]
I've never done this before, but the setup looks reasonable.

**Comment by tschwinge** [comment]
This resolves #2882 "Locally provide crates that `libgrust` depends on".

**Comment by tschwinge** [comment]
> Note that this was simply generated with `cargo vendor`

Please add a file `libgrust/libformat_parser/vendor.NOTES` (or similar) about how this has been created, how to update, etc.  Compare: `gcc/d/README.gcc`, `libgo/README.gcc`, `libphobos/README.gcc`, `libsanitizer/HOWTO_MERGE`, etc.

**Comment by CohenArthur** [comment]
> > Note that this was simply generated with `cargo vendor`
> 
> Please add a file `libgrust/libformat_parser/vendor.NOTES` (or similar) about how this has been created, how to update, etc. Compare: `gcc/d/README.gcc`, `libgo/README.gcc`, `libphobos/README.gcc`, `libsanitizer/HOWTO_MERGE`, etc.

done in the latest version :) thanks

**Pull request merged**
