### PR TITLE
docker: Add commit information to Docker image

### LINKED ISSUE #1262: Upload more information in docker image
Extra info such as the commit used when building the project and so on

### PR DESCRIPTION
**Pull request by CohenArthur**
Closes #1262

### CODE REVIEW

**Comment by CohenArthur** [comment]
Example info (for now!):
```sh
arthur@platypus ~/G/r/gccrs (add-commit-info-to-dockerfile)> docker run --rm -it gccrs
root@326cc71708c6:/# cat GCCRS_BUILD
7b96da9a45b
```
This will be helpful for the testing runs

**Review by philberty — APPROVED** [review]
nice one

**Pull request merged**
