### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by tschwinge**

### CODE REVIEW

**Comment by tschwinge** [comment]
By the way: this must of course not be rebased by GitHub merge queue, but has to become a proper Git merge.

**Comment by powerboat9** [comment]
@tschwinge Nice work, how did you figure out we needed ```tm_p.h```?

**Comment by tschwinge** [comment]
> how did you figure out we needed `tm_p.h`?

Basically like this: the #1819 `error: 'rs6000_xcoff_strip_dollar' was not declared` needs `[source]/gcc/config/rs6000/rs6000-protos.h` and the #1864 `error: 'pdp11_gen_int_label' was not declared` needs `[source]/gcc/config/pdp11/pdp11-protos.h`, so there should exist some *indirection header file* that does `#include "[target]-protos.h"`.  That *indirection header file* probably is generated at build time (because then we can easily expand `[target]`).  Then I found `[build]/gcc/tm_p.h` to be doing exactly that, and confirmed via other existing `#include "tm_p.h"` usage that this is a correct thing to do.

**Comment by CohenArthur** [comment]
Looks good to me :) thank you @tschwinge. @jbglaw we'll merge this and if your github remote build passes we'll close both issues :)

**Comment by jbglaw** [comment]
Just did a pull, wasn't yet there. Once I realize it's there (or you drop me a comment?) I'll schedule a new round for my gccrs builds. It' all in place, so it's easy. ^^

**Comment by jbglaw** [comment]
Hi @CohenArthur , just updated the other two tickets: I got confirmation that the three builds (pdp11 and the two powerpc AIX versions) had a successful run.

**Pull request merged**
