### PR TITLE
Move rust-buffered-queue.h to util folder #1766

### LINKED ISSUE #1766: Refactor rust-buffered-queue.h
This is a util class and should be moved into the util folder.

### PR DESCRIPTION
**Pull request by drmahad**
### gcc/rust/ChangeLog:

- 	rust-buffered-queue.h
- 	Moved to util/rust-buffered-queue.h.

Signed-off-by: Muhammad Mahad <mahadtxt@gmail.com>

### CODE REVIEW

**Review by philberty — APPROVED** [review]
LGTM

**Comment by CohenArthur** [comment]
bors cancel

The commit checker isn't happy yet

**Comment by CohenArthur** [comment]
Great stuff, thank you @drmahad :) We're making that whole Changelog process more bearable, sorry for the annoyance.

bors r+

**Pull request merged**
