### PR TITLE
tests/attr_cold: fix a typo

### PR DESCRIPTION
**Pull request by liushuyu**
- fix a typo in the `rust/compile/attr_cold.rs` file

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]

**Comment by CohenArthur** [comment]
We should definitely add something to the CI because this should have been caught :D

**Comment by liushuyu** [comment]
> We should definitely add something to the CI because this should have been caught :D

Improvements done in #1162

**Review by philberty — APPROVED** [review]
LGTM

**Pull request merged**
