### PR TITLE
WIP : AST node for inline assembly

### PR DESCRIPTION
**Pull request by mvvsmk**
Addresses issue #1567  . Added node. Please tell me if there is anything more I could add to this class definition. Below I explain a few decisions and a few doubts I had regarding a few identifiers in the rustc code and their equivalent in gccrs.

In the rustc compiler, the Inline ASM node has been implemented [here](https://rustc-dev-guide.rust-lang.org/asm.html#ast)

I have done what I could to mimic its properties. In rust, we can have enums with different implementations. Like here, if It's an InlineAsm operand, It could be IN with 2 attributes, while if it were OUT it would have 3 attributes, so I implemented each of these as separate structs.
 
There are a few things I still need clarification on. Like the identifiers: options and span(this is analogous to the scope from exploring the rustc compiler further), and am particularly struggling with these lines to find its equivalent cpp code.

` pub template_strs: Box<[(Symbol, Option<Symbol>, Span)]> `
`pub clobber_abi: Option<(Symbol, Span)>`

I have also added location data to the following structs, though no such thing was done in the rustc implementation because it might be helpful later
- InlineAsmSym
- InlineAsmRegOrClass
- InlineAsmPlaceHolder
- InlineAsmTemplatePiece (I didn't add this one yet, if you agree to the above, I'll add location data here too)

I also experimented with adding visitors, that's why there are changes in the following files, as I was asked just to create the class I will remove these changes in my final PR:
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-early-name-resolver.h
- gcc/rust/ast/rust-ast-visitor.h

### CODE REVIEW

**Comment by mvvsmk** [comment]
Hey @CohenArthur I have added the two statements as you requested here

> But for our use case, at least at first, we can replace this with std::vector.
The tuple is simply an anonymous struct containing a Symbol, an optional Symbol and a location. We don't really have tuples in C++, so we can use a regular struct or class instead. We don't have a proper Symbol class yet, so we'll use std::strings here.
>pub clobber_abi: Option<(Symbol, Span)>
> Similarly, this is an optional string with location info

do go through it once, would you like me to add anything else, like specific variable or member function implementations? I tied using **'std::tuple'** but your idea of adding a struct sounded better, hence I went with it.

> Overall I think this is a great start :) do my answers help make it a little clearer?

Yes, yes, they do make it more clear. Thank you for helping me out. :)

**Comment by CohenArthur** [comment]
> github prompted me to update my own main branch, but when I told it to do so it prompted me that I didn't have access, I think it was trying to pull into the main gccrs, ig it was done accidentally hope it didn't cause any problems.

I think that's alright :) 

I'm good with merging this in this state and maybe refining it later down the line when we start using it. We do need to take care of the changelog issues and rebase this PR's commits tho :) let me know if you need help doing that!

Thank you for working on this I really appreciate it. Would you be interested in doing the same discovery work regarding the HIR equivalent node?

**Comment by mvvsmk** [comment]
> I'm good with merging this in this state and maybe refining it later down the line when we start using it. We do need to take care of the changelog issues and rebase this PR's commits tho :) let me know if you need help doing that!

It's my first time making a change log, I went on GCC's website, and it told me to run the mklog.py script, which would auto-generate the changelog and add it. But in my case, it's spitting an error.

``` 
❯ ./contrib/mklog.py
Traceback (most recent call last):
  File "/home/achilles/code/gccrs/./contrib/mklog.py", line 40, in <module>
    from unidiff import PatchSet
ModuleNotFoundError: No module named 'unidiff' 
```

Could you help me with this? Any documentation/blog/guide would also help me out, I searched online and I am getting a lot of npm packages for auto generation of changelog cli do I need to go through them?...

My current work flow has been 
make a new branch  -> make changes -> build the project -> commit changes -> rebase any additional commits -> push ->PR.

Are there any additional hooks I need to incorporate when I commit? or any small changes I need to make to my workflow?

> Would you be interested in doing the same discovery work regarding the HIR equivalent node?

As I understand, you want me to create another class/node but this time in the HIR for inline ASM. I would love to work on it :). Do create an Issue for it. I'll get on it as soon as I finish this PR.

**Comment by mvvsmk** [comment]
@CohenArthur I figured out what was going wrong. It had to do with the 'gcc-git-customization.sh' file. After rebase-ing all the commits into one and adding the change log, I will close this PR and create a new one.

**Comment by CohenArthur** [comment]
Sorry for taking so long to answer!

> > I'm good with merging this in this state and maybe refining it later down the line when we start using it. We do need to take care of the changelog issues and rebase this PR's commits tho :) let me know if you need help doing that!
> 
> It's my first time making a change log, I went on GCC's website, and it told me to run the mklog.py script, which would auto-generate the changelog and add it. But in my case, it's spitting an error.
> 
> ```
> ❯ ./contrib/mklog.py
> Traceback (most recent call last):
>   File "/home/achilles/code/gccrs/./contrib/mklog.py", line 40, in <module>
>     from unidiff import PatchSet
> ModuleNotFoundError: No module named 'unidiff' 
> ```
> 
> but when I pip installed the required packages it doesn't give any output, it just timesout.

Yes, `mklog.py` takes a patch content as input. So you can do something like `git show -1 | mklog.py`. But as you mention later on, it's easier to run `git gcc-commit-mklog`.

> Could you help me with this? Any documentation/blog/guide would also help me out, I searched online and I am getting a lot of npm packages for auto generation of changelog cli do I need to go through them?...

No worries, no need for npm packages - just `git gcc-commit-mklog`

> My current work flow has been make a new branch -> make changes -> build the project -> commit changes -> rebase any additional commits -> push ->PR.

This is good! I think the one thing you could look into is that you don't need to make a new PR everytime you rebase. Let's take a look at this PR:

* You have a branch, called Issue_1567
* You pushed it and opened a PR
* In the meantime, contributors pushed and merged multiple PRs into master
* To update your branch, you can simply fetch the upstream remote ([more info here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line))
* Then if you run into any conflicts, resolve them
* Finally, force update your branch with `git push -f`

> Are there any additional hooks I need to incorporate when I commit? or any small changes I need to make to my workflow?

I think using `git gcc-commit-mklog` instead of `git commit` is a very good tip if you're using git on the command line. Otherwise, your workflow is perfectly fine to me.

> > Would you be interested in doing the same discovery work regarding the HIR equivalent node?
> 
> As I understand, you want me to create another class/node but this time in the HIR for inline ASM. I would love to work on it :). Do create an Issue for it. I'll get on it as soon as I finish this PR.

Great :D Here is the issue: #1568

> @CohenArthur I figured out what was going wrong. It had to do with the 'gcc-git-customization.sh' file. After rebase-ing all the commits into one and adding the change log, I will close this PR and create a new one.

It's fine if you'd rather force update this PR's branch instead :) sorry that this is all so difficult. We're working towards more explaining of Changelogs and how to write them and so on.

**Comment by mvvsmk** [comment]
> Yes, mklog.py takes a patch content as input. So you can do something like git show -1 | mklog.py. But as you mention later on, it's easier to run git gcc-commit-mklog.

Thank you for being patient with me and answering my doubts :). I have experimented more with git show -1 | mklog.py and discovered the -s option in gcc-commit-mklog.

> This is good! I think the one thing you could look into is that you don't need to make a new PR everytime you rebase. Let's take a look at this PR:
> 
> You have a branch, called Issue_1567
> You pushed it and opened a PR
> In the meantime, contributors pushed and merged multiple PRs into master
> To update your branch, you can simply fetch the upstream remote ([more info here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line))
> Then if you run into any conflicts, resolve them
> Finally, force update your branch with git push -f

I tried this first with `git rebase -i HEAD~2` after `git fetch upstream remote`. I could see there were a lot of conflicts as by branch was 1044 commits behind XD, so I just `git reset` to a previous commit and then force-pushed it upstream. I learned a lot about the three trees of git in the process.

I created a PR with the correct change log finally XD, check it out and tell me if there is anything else I could do :) .

**Pull request closed without merging**
