### PR TITLE
Merge GCC mainline/master into gccrs/master

### PR DESCRIPTION
**Pull request by ibuclaw**
As per title, pull in the latest and greatest from gcc development.

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
@ibuclaw thanks a lot for this! It's really helpful. I have no idea why our MacOS build fails in building libunwind. I'll have a look later on. I'm okay with merging this even with the MacOS failure but waiting for more input

**Comment by tschwinge** [comment]
```
2022-09-24T19:09:17.3973890Z In file included from ../../../libgcc/config/unwind-dw2-fde-darwin.c:27:
2022-09-24T19:09:17.4027160Z ../../../libgcc/unwind-dw2-fde.c: In function ‘__deregister_frame_info_bases’:
2022-09-24T19:09:17.4031700Z ../../../libgcc/unwind-dw2-fde.c:287:15: error: ‘in_shutdown’ undeclared (first use in this function)
2022-09-24T19:09:17.4075590Z   287 |   gcc_assert (in_shutdown || ob);
2022-09-24T19:09:17.4128400Z       |               ^~~~~~~~~~~
2022-09-24T19:09:17.4133290Z ../../../libgcc/../gcc/tsystem.h:122:36: note: in definition of macro ‘gcc_assert’
2022-09-24T19:09:17.4176800Z   122 | #define gcc_assert(EXPR) ((void)(!(EXPR) ? abort (), 0 : 0))
2022-09-24T19:09:17.4229550Z       |                                    ^~~~
2022-09-24T19:09:17.4234830Z ../../../libgcc/unwind-dw2-fde.c:287:15: note: each undeclared identifier is reported only once for each function it appears in
2022-09-24T19:09:17.4252620Z   287 |   gcc_assert (in_shutdown || ob);
2022-09-24T19:09:17.4253380Z       |               ^~~~~~~~~~~
2022-09-24T19:09:17.4254390Z ../../../libgcc/../gcc/tsystem.h:122:36: note: in definition of macro ‘gcc_assert’
2022-09-24T19:09:17.4255280Z   122 | #define gcc_assert(EXPR) ((void)(!(EXPR) ? abort (), 0 : 0))
2022-09-24T19:09:17.4256020Z       |                                    ^~~~
2022-09-24T19:09:17.4256990Z make[2]: *** [unwind-dw2-fde-darwin.o] Error 1
```

Looks like another instance of <https://gcc.gnu.org/PR107026> "gcc_assert (in_shutdown || ob); build failure for i586-msdosdjgpp target" to me.

**Comment by ibuclaw** [comment]
> @ibuclaw, should edit submission text, as that ends up in the Git log?

Remove everything above the line?

**Comment by philberty** [comment]
@ibuclaw when you open PR we have that wee list of items for new contributors we ask people to remove that otherwise it ends up in the merge commit. I've done it for you this time :).

We don't gate merging on macos but we should raise this build failure as an issue locally as I know some people like to dev on a x86 ,mac.

**Comment by ibuclaw** [comment]
> @ibuclaw when you open PR we have that wee list of items for new contributors we ask people to remove that otherwise it ends up in the merge commit. I've done it for you this time :).
> 
> We don't gate merging on macos but we should raise this build failure as an issue locally as I know some people like to dev on a x86 ,mac.

Based on the comments from the reference PR in gcc, the fix will land sometime today/tomorrow, so can just merge again after that's in.

**Pull request merged**
