### PR TITLE
Check for writes outside of the build directory

### PR DESCRIPTION
**Pull request by powerboat9**
I noticed that ```libgrust/libformat_parser/target``` was seemingly generated outside the build directory on my machine. This should detect similar issues, and confirm/deny the aforementioned issue.

### CODE REVIEW

**Comment by P-E-P** [comment]
@powerboat9 The MacOS CI broke, we repaired it but you need to rebase your branch now.

**Comment by tschwinge** [comment]
That specific issue was addressed by #2947 "Move 'libformat_parser' build into the GCC build directory, and into libgrust" -- but yes, good idea to actually make sure we're not introducing similar things again!  :+1:

**Review by tschwinge — CHANGES_REQUESTED** [review]
Instead of `chmod -R a-w *`, it's good practice to use `chmod -R a-w ./*` (or something similar) -- or just `chmod -R a-w .` in fact :upside_down_face: -- so that "malicious" files starting with `-` can't possibly affect the `chmod` command.

**Comment by tschwinge** [comment]
Eh, the build now actually *is failing* due to a similar issue:

```
cargo build --manifest-path ../../gcc/rust/checks/errors/borrowck/ffi-polonius/Cargo.toml --release --target-dir rust/ffi-polonius
    Updating crates.io index
error: failed to write /home/runner/work/gccrs/gccrs/gcc/rust/checks/errors/borrowck/ffi-polonius/Cargo.lock
```

...., so that'll need to be addressed first (in a similar way as #2947 "Move 'libformat_parser' build into the GCC build directory, and into libgrust", I suppose).

**Comment by powerboat9** [comment]
From what I see from ```man``` documentation the ```chmod``` command doesn't accept flags after the mode(s) are given, but I'll change it just in case.

**Comment by tschwinge** [comment]
It's easy enough to try:

```
$ ls -l
total 0
-rw-r--r-- 1 thomas thomas 0 May  8 10:50 --verbose
-rw-r--r-- 1 thomas thomas 0 May  8 10:50 foo
$ chmod -R a-w *
mode of 'foo' changed from 0644 (rw-r--r--) to 0444 (r--r--r--)
$ ls -l
total 0
-rw-r--r-- 1 thomas thomas 0 May  8 10:50 --verbose
-r--r--r-- 1 thomas thomas 0 May  8 10:50 foo
```

**Comment by P-E-P** [comment]
Looks like cargo is trying to update the lock file and fail. I've noticed ffi-polonius does not use the same cargo config as libformat parser. Maybe we should update the cargo invocation with a `--config` argument ?

**Comment by thesamesam** [comment]
I think it's worth creating a Cargo.toml file.

In Gentoo, in cargo.eclass, we do:
```
cat > "${ECARGO_HOME}/config.toml" <<- _EOF_ || die "Failed to create cargo config"
[source.gentoo]
directory = "${ECARGO_VENDOR}"

[source.crates-io]
replace-with = "gentoo"
local-registry = "/nonexistent"

[net]
offline = true

[build]
jobs = $(makeopts_jobs)
incremental = false

[term]
verbose = true
$([[ "${NOCOLOR}" = true || "${NOCOLOR}" = yes ]] && echo "color = 'never'")
$(_cargo_gen_git_config)
_EOF_

export CARGO_HOME="${ECARGO_HOME}"
```

You don't need the local registry bit, but you get the idea wrt offline.

**Comment by powerboat9** [comment]
It looks like the issues preventing this PR from passing checks have since been fixed

**Review by P-E-P — APPROVED** [review]

**Pull request merged**
