### PR TITLE
shebang handling

### PR DESCRIPTION
**Pull request by dkm**
Mark Wielaard:
> Shebang handling, the first line starting with #! was not done fully
> correct and it isn't necessary to keep track of the shebang line in
> the AST or HIR Crate classes.
> 
> Because an inner attribute also starts with #! the first line isn't
> regarded as a shebang line if the #! is followed by (optional)
> whitespace and comments and a [. In that case the #! is seen as the
> start of an inner attribute.
> 
> I added various testcases that hopefully show the funny things you can
> get when the first line starts with #!.

### CODE REVIEW

**Comment by bjorn3** [comment]
I presume this is from the mailinglist? Could you link to the respective archive in the future when taking a patch from the mailinglist?

**Comment by dkm** [comment]
Sure! Will do for the future ones.
https://gcc.gnu.org/pipermail/gcc-rust/2021-July/000068.html

**Comment by bjorn3** [comment]
Thanks!

**Review by philberty — APPROVED** [review]
LGTM

**Pull request merged**
