### PR TITLE
Modify parser error message reporting system to allow recovery

### PR DESCRIPTION
**Pull request by SimplyTheOther**
Basically, this modifies the parser error message reporting system to create `Error` structs instead of directly calling `rust_error_at`, so that errors can be ignored if need be. This effectively allows backtracking, which is useful for macro expansion and possibly regular parsing in the future. 

This was implemented by having a stored error table per `Parser` instance, and then emitting the stored errors if desired after parsing has completed. This should allow several parsers to coexist without issues relating to error handling.

Addresses #224

### CODE REVIEW

**Comment by bjorn3** [comment]
@SimplyTheOther The username `@redbrain` has been registered by someone else. You may want to update your remote url.

**Comment by SimplyTheOther** [comment]
> 
> 
> @SimplyTheOther The username `@redbrain` has been registered by someone else. You may want to update your remote url.

Thanks for the heads-up. I have now changed it in my local repo.

**Comment by philberty** [comment]
Yeah I used to use that username a few years ago but I forgot to keep my blog going and it got registered by some shopping webapp lol. My wife calls me philbert so I thought I would try and stick with that.

**Review by philberty — APPROVED** [review]
nice one

**Pull request merged**
