### PR TITLE
Move 'libformat_parser' build into the GCC build directory, and into libgrust

### PR DESCRIPTION
**Pull request by tschwinge**
..., as discussed in #2883 "Move `cargo build` into the GCC build directory".

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
LGTM, thank you :)

**Comment by CohenArthur** [comment]
not sure why the Remark step of the CI is failing... this has nothing to do with your changes anyway

**Comment by tschwinge** [comment]
@CohenArthur: Do I get your permission to also directly integrate upstream such changes, in order to incrementally pave the way for adding 'libformat_parser' directly in libgrust, without the broken intermediate steps?

**Comment by CohenArthur** [comment]
> @CohenArthur: Do I get your permission to also directly integrate upstream such changes, in order to incrementally pave the way for adding 'libformat_parser' directly in libgrust, without the broken intermediate steps?

of course! please do :) then I'm guessing we'll also upstream #2942 that way?

**Pull request merged**
