### PR TITLE
tests: Improve timeout handling

### PR DESCRIPTION
**Pull request by liushuyu**
- add a 10-second timeout for individual compile test
- add a xfail test case to ensure the timeout mechanism is working

### CODE REVIEW

**Comment by liushuyu** [comment]
This patch is although a hack, could help to prevent issues like:

- #1102 
- #1084 

In fact, the added XFAIL test case is from #1084.

**Review by philberty — APPROVED** [review]
This seems good to me but I would rather @dkm or @tschwinge approve/merge this one since they have more experience than me here.

**Comment by CohenArthur** [comment]
Since the test case is passing, wouldn't that cause the same issue of having potentially infinite-looping code merged into master? It seems the only extra output is `WARNING: program timed out` which we should handle properly to report as a CI failure

**Comment by liushuyu** [comment]
> Since the test case is passing, wouldn't that cause the same issue of having potentially infinite-looping code merged into master? It seems the only extra output is `WARNING: program timed out` which we should handle properly to report as a CI failure

As you can see, the test case is an `XFAIL` test case where it's expected to fail. In reality, timing out would produce an excess error with no error location (no line number). In which case, if your test case is well-written (does not have a catch-all case for excess errors), timing out will fail the CI.

**Pull request merged**
