### PR TITLE
Revert 10-second timeout for each test

### PR DESCRIPTION
**Pull request by Parthib314**
* Fixes issue #1747 

**Remove the 10-second timeout for each compile case**

### CODE REVIEW

**Comment by Parthib314** [comment]
Hey @CohenArthur if you have time then please review this PR.

**Comment by philberty** [comment]
Hi @Parthib314 you need to edit your top message to remove the checklist as all of this info will be contained within your merge commit which is not what we want.

Also I am not sure why we are removing the timeout, I guess it must be something from the gcc-upstream review. @dkm or @tschwinge any thoughts?

**Comment by Parthib314** [comment]
@philberty Is this correct now???

**Comment by CohenArthur** [comment]
> Also I am not sure why we are removing the timeout, I guess it must be something from the gcc-upstream review. @dkm or @tschwinge any thoughts?

@philberty Upon fixing the testsuite for Windows, we realized that no other frontends were setting timeouts this way. There should already be (if I'm not mistaken) a 300 seconds timeout (so 5 minutes), which makes much more sense considering some tests might take longer than 10 seconds to run on slower machines. IIRC, the original commit was also added as a "hack" to circumvent some tests looping infinitely, and maybe we just didn't wait long enough for the 5 minutes timeout to kick in? But the current testsuite passes properly.

**Review by CohenArthur — APPROVED** [review]

**Comment by philberty** [comment]
@CohenArthur ah ok yes thats right i forgot about the default timeout of 300 seconds. Lets add your comment to the issue.

**Pull request merged**
