### PR TITLE
Merge GCC mainline/master into gccrs/master (and port Rust target documentation to RST)

### PR DESCRIPTION
**Pull request by ibuclaw**
All documentation in upstream gcc has been converted to Sphinx/RST.  As well as merging this downstream, have gone through the existing documentation (currently only rust target macros) and ported them over to RST in https://github.com/Rust-GCC/gccrs/pull/1637/commits/69e8233d22352c41801b7f4668403d9e5903ad3e.

### CODE REVIEW

**Comment by tschwinge** [comment]
Gah, GCC upstream again reverted back from Sphinx to Texinfo: <https://gcc.gnu.org/PR107655> etc., so your work on *rust: sphinx: Port Rust target macros documentation to RST* was all in vain.  :-(

**Comment by ibuclaw** [comment]
> Gah, GCC upstream again reverted back from Sphinx to Texinfo: https://gcc.gnu.org/PR107655 etc., so your work on _rust: sphinx: Port Rust target macros documentation to RST_ was all in vain. :-(

Oh noes!  I hope they don't get rid of the D online docs, I've been waiting nearly 5 years for them to publish them. :-)

**Comment by ibuclaw** [comment]
i'll switch this over to a draft, on the assumption that people will give Spinx a try again beginning 14.x development.

**Comment by dkm** [comment]
> i'll switch this over to a draft, on the assumption that people will give Sphinx a try again beginning 14.x development.

Looks like this will not happen. But we can still have our docs in sphinx and simply generate the texinfo files.

**Comment by ibuclaw** [comment]
Oh wow, this is old. Rust is already in GCC, so I guess you don't need these merge PRs anymore.

**Pull request closed without merging**
