### PR TITLE
Modifying Readme File

### PR DESCRIPTION
**Pull request by anuragcs**
This is a simple change in readme file regarding the current ongoing project.

As a beginner I am starting with basics and will dive in more to resolve issues and present my solutions in the domain I am proficient at.

### CODE REVIEW

**Review by CohenArthur — COMMENTED** [review]
This is GCC's README, not gccrs' README :D our Readme file that is displayed on the repo's page is README.md. If you'd like to modify this file, you will need to send patches to GCC's mailing list and go through their contributing process :)

**Comment by anuragcs** [comment]
Alright, I am still learning so thanks for suggestion I will do it in a correct way

**Comment by CohenArthur** [comment]
@anuragcs do you want to modify this PR or should we close it for now?

**Comment by anuragcs** [comment]
You can close this PR, I will be creating a new one in accordance with contributing guidelines and try to solve the issues mentioned.

**Pull request closed without merging**
